### PR TITLE
Climate on demand

### PR DESCRIPTION
**Pull request by stevvseah**
Created ClimateConnector class to house all functions to be used in Climate On Demand recipe.

Created the following functions:
- check_is_dms
- dms_to_decimal
- chunk_list
- get_lat
- get_lon
- new_token
- get_scores
- colname_splitter

### CODE REVIEW

**Review by jieqiangt — CHANGES_REQUESTED** [review]
There are methods that do not require self as an arguments that are supposed to be static methods, like the check _is_dms. Shift those functions out if they can actually be used in other scripts or make it a static function.

**Comment by stevvseah** [comment]
> There are methods that do not require self as an arguments that are supposed to be static methods, like the check _is_dms. Shift those functions out if they can actually be used in other scripts or make it a static function.

Updated those functions to be static and moved them to utils since they are not specific to climate_on_demand!

**Review by jieqiangt — APPROVED** [review]
Looks good! You can merge to master then

**Comment by jieqiangt** [comment]
@stevvseah do note that you still need to have the script in dataiku to call those funtions to complete the user story.

**Pull request merged**
